/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.paymentsystem.view;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Component;
import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.Window;
import java.time.LocalDate;
import javax.swing.SwingUtilities;
import lk.ijse.paymentsystem.dto.CourseDetailsDTO;
import lk.ijse.paymentsystem.dto.RegistrationDTO;
import lk.ijse.paymentsystem.dto.StudentDTO;

/**
 *
 * @author simo-ds
 */
public class CourseDetails extends javax.swing.JFrame {

    /**
     * Creates new form CourseDetails
     */
    public CourseDetails(){
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
    }
    
    StudentDTO student;
    CourseDetailsDTO courseDetailsDTO;
    CourseDetailsController controller;
    
    private StudentRegistrationCourseDetailForm studentRFC;
    public CourseDetails(StudentDTO student,StudentRegistrationCourseDetailForm studentRCF) {
        initComponents();
        controller=new CourseDetailsController();
        this.studentRFC = studentRCF;
        this.student=student;
        this.getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(2);
        initComponents2();
    }
    
    private void initComponents2(){
        for (String courseName : controller.getCourseNames()) {
            cmbBxAcademicPrograms.addItem(courseName);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        rbtnBcs = new javax.swing.JCheckBox();
        lblWith = new javax.swing.JLabel();
        cmbBxAcademicPrograms = new javax.swing.JComboBox<>();
        lblAcademicPrograms = new javax.swing.JLabel();
        lblCourseAppliedFor = new javax.swing.JLabel();
        lblCourseAppliedFor1 = new javax.swing.JLabel();
        lblAcademicPrograms1 = new javax.swing.JLabel();
        lblAcademicPrograms2 = new javax.swing.JLabel();
        lblAcademicPrograms3 = new javax.swing.JLabel();
        lblAcademicPrograms4 = new javax.swing.JLabel();
        lblAcademicPrograms5 = new javax.swing.JLabel();
        lblAcademicPrograms6 = new javax.swing.JLabel();
        btnAddStudent = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        lblCourseName = new javax.swing.JLabel();
        lblCourseDuration = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        lblFee = new javax.swing.JLabel();
        cmbBxBatches = new javax.swing.JComboBox<>();
        lblDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/paymentsystem/images/ijse-logo.gif"))); // NOI18N

        rbtnBcs.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        rbtnBcs.setText("BCS (British Computer Society)");
        rbtnBcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnBcsActionPerformed(evt);
            }
        });

        lblWith.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblWith.setText("With");

        cmbBxAcademicPrograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBxAcademicProgramsActionPerformed(evt);
            }
        });

        lblAcademicPrograms.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblAcademicPrograms.setText("Academic Programs:");

        lblCourseAppliedFor.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblCourseAppliedFor.setText("COURSE APPLIED FOR");

        lblCourseAppliedFor1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblCourseAppliedFor1.setText("COURSE DETAILS");

        lblAcademicPrograms1.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblAcademicPrograms1.setText("Course Name :");

        lblAcademicPrograms2.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblAcademicPrograms2.setText("Batch :");

        lblAcademicPrograms3.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblAcademicPrograms3.setText("Duration :");

        lblAcademicPrograms4.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblAcademicPrograms4.setText("Course Fee :");

        lblAcademicPrograms5.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblAcademicPrograms5.setText("No Of Semesters :");

        lblAcademicPrograms6.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblAcademicPrograms6.setText("Starting Date :");

        btnAddStudent.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/paymentsystem/icons/add.png"))); // NOI18N
        btnAddStudent.setMnemonic('A');
        btnAddStudent.setText("Do Payment");
        btnAddStudent.setToolTipText("Click to add a new student");
        btnAddStudent.setPreferredSize(new java.awt.Dimension(127, 39));
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });
        btnAddStudent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnAddStudentKeyReleased(evt);
            }
        });

        btnGoBack.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/paymentsystem/icons/back1600 edit.png"))); // NOI18N
        btnGoBack.setMnemonic('G');
        btnGoBack.setText("Go Back");
        btnGoBack.setToolTipText("Click to add a new student");
        btnGoBack.setPreferredSize(new java.awt.Dimension(127, 39));
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        btnGoBack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnGoBackKeyReleased(evt);
            }
        });

        lblCourseName.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblCourseName.setText("name");

        lblCourseDuration.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblCourseDuration.setText("years");

        lblSemester.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblSemester.setText("semesters");

        lblFee.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblFee.setText("fee");

        cmbBxBatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBxBatchesActionPerformed(evt);
            }
        });

        lblDate.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblDate.setText("date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 347, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCourseAppliedFor)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAcademicPrograms)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAcademicPrograms2)
                                            .addComponent(lblAcademicPrograms1)
                                            .addComponent(lblAcademicPrograms3)
                                            .addComponent(lblAcademicPrograms4)
                                            .addComponent(lblAcademicPrograms5)
                                            .addComponent(lblAcademicPrograms6))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBxAcademicPrograms, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCourseName)
                            .addComponent(lblCourseDuration)
                            .addComponent(lblSemester)
                            .addComponent(lblFee)
                            .addComponent(cmbBxBatches, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(lblWith))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(rbtnBcs))
                    .addComponent(lblCourseAppliedFor1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCourseAppliedFor)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcademicPrograms)
                    .addComponent(cmbBxAcademicPrograms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWith)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnBcs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCourseAppliedFor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcademicPrograms1)
                    .addComponent(lblCourseName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcademicPrograms2)
                    .addComponent(cmbBxBatches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcademicPrograms3)
                    .addComponent(lblCourseDuration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcademicPrograms5)
                    .addComponent(lblSemester))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcademicPrograms6)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcademicPrograms4)
                    .addComponent(lblFee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnBcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnBcsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnBcsActionPerformed

    private void cmbBxAcademicProgramsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBxAcademicProgramsActionPerformed
        cmbBxBatches.removeAllItems();
        for (String batchDetail : controller.getBatchDetails(cmbBxAcademicPrograms.getSelectedIndex())) {
            cmbBxBatches.addItem(batchDetail);
        }
    }//GEN-LAST:event_cmbBxAcademicProgramsActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        RegistrationDTO rdto=new RegistrationDTO(controller.getBatchID(cmbBxBatches.getSelectedIndex()), LocalDate.now(), rbtnBcs.isSelected());
        PaymentForRegistrationCourse paymentForm = new PaymentForRegistrationCourse(student,courseDetailsDTO,rdto);
        paymentForm.setVisible(true);
        studentRFC.dispose();
        this.dispose();
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnAddStudentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddStudentKeyReleased
//        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
//            btnGoBack.requestFocusInWindow();
//        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
//            btnGoBack.requestFocusInWindow();
//        }
    }//GEN-LAST:event_btnAddStudentKeyReleased

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnGoBackKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGoBackKeyReleased
//        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
//            btnAddStudent.requestFocusInWindow();
//        } else if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
//            btnAddStudent.requestFocusInWindow();
//        }
    }//GEN-LAST:event_btnGoBackKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        KeyboardFocusManager focusManager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        focusManager.addKeyEventPostProcessor(new KeyEventPostProcessor() {
            @Override
            public boolean postProcessKeyEvent(java.awt.event.KeyEvent e) {
                if (e.getID() == java.awt.event.KeyEvent.KEY_RELEASED) {
                    if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                        Window windowForComponent = SwingUtilities.windowForComponent((Component) e.getSource());
                        if (windowForComponent == null) return false;
                        windowForComponent.dispose();
                    }
                }
                return false;
            }
        });
    }//GEN-LAST:event_formWindowOpened

    private void cmbBxBatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBxBatchesActionPerformed
        courseDetailsDTO=controller.getCourseDetails(cmbBxBatches.getSelectedIndex());
        
        lblDate.setText((controller.getBatchStartDate(cmbBxBatches.getSelectedIndex())).toString());
        lblCourseName.setText(courseDetailsDTO.getName());
        lblSemester.setText(""+courseDetailsDTO.getNo_of_Semesters());
        lblCourseDuration.setText("Approx. "+(courseDetailsDTO.getNo_of_Semesters()*6)+" months");
        lblFee.setText(""+courseDetailsDTO.getCourseFee());
    }//GEN-LAST:event_cmbBxBatchesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JComboBox<String> cmbBxAcademicPrograms;
    private javax.swing.JComboBox<String> cmbBxBatches;
    private javax.swing.JLabel lblAcademicPrograms;
    private javax.swing.JLabel lblAcademicPrograms1;
    private javax.swing.JLabel lblAcademicPrograms2;
    private javax.swing.JLabel lblAcademicPrograms3;
    private javax.swing.JLabel lblAcademicPrograms4;
    private javax.swing.JLabel lblAcademicPrograms5;
    private javax.swing.JLabel lblAcademicPrograms6;
    private javax.swing.JLabel lblCourseAppliedFor;
    private javax.swing.JLabel lblCourseAppliedFor1;
    private javax.swing.JLabel lblCourseDuration;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFee;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblWith;
    private javax.swing.JCheckBox rbtnBcs;
    // End of variables declaration//GEN-END:variables
}
