/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.paymentsystem.view;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.Window;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author Ranjith Suranga
 */
public class ManagePayment extends javax.swing.JDialog {

    /**
     * Creates new form ManageStudents
     */
    public static ManagePayment manageStudents;
    
    
    private ManagePayment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        

//        ImageIcon frameIcon = new ImageIcon(this.getClass().getResource("/lk/ijse/academic_results_system_admin/icons/frame_icon_manage_students.png"));
//        setIconImage(frameIcon.getImage());

        getContentPane().setBackground(new Color(0xFFFFFF));

        for (Component cmp : this.getContentPane().getComponents()) {
            if (cmp instanceof JButton) {
                JButton btn = (JButton) cmp;
                btn.setFocusPainted(false);
                btn.addFocusListener(new FocusAdapter() {

                    @Override
                    public void focusGained(FocusEvent e) {
                        super.focusGained(e);
                        btn.setFont(btn.getFont().deriveFont(Font.BOLD));
                        btn.setForeground(new Color(0x0000FF));
                    }

                    @Override
                    public void focusLost(FocusEvent e) {
                        super.focusLost(e);
                        btn.setFont(btn.getFont().deriveFont(Font.PLAIN));
                        btn.setForeground(new Color(0x000000));
                    }
                    
                });
            }
        }
    }

    public static ManagePayment showInstance(java.awt.Frame parent, boolean modal){
        if(manageStudents==null){
            manageStudents = new ManagePayment(parent, modal);
        }
        manageStudents.setVisible(true);
        return manageStudents;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddNewStudent = new javax.swing.JButton();
        btnSearchExistingStudent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Students | IJSE - Academic Results System");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnAddNewStudent.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAddNewStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/paymentsystem/icons/add_new_student.png"))); // NOI18N
        btnAddNewStudent.setText("Course Payment");
        btnAddNewStudent.setToolTipText("Click to add a new student");
        btnAddNewStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewStudentActionPerformed(evt);
            }
        });
        btnAddNewStudent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnAddNewStudentKeyReleased(evt);
            }
        });

        btnSearchExistingStudent.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSearchExistingStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/paymentsystem/icons/search_existing_student.png"))); // NOI18N
        btnSearchExistingStudent.setText("Fine Payment");
        btnSearchExistingStudent.setToolTipText("Click to search a student and then edit or delete him/her");
        btnSearchExistingStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchExistingStudent.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSearchExistingStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchExistingStudentActionPerformed(evt);
            }
        });
        btnSearchExistingStudent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnSearchExistingStudentKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddNewStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchExistingStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnAddNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchExistingStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddNewStudent, btnSearchExistingStudent});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewStudentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddNewStudentKeyReleased
//        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
//            btnSearchExistingStudent.requestFocusInWindow();
//        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
//            btnViewAllStudents.requestFocusInWindow();
//        }
    }//GEN-LAST:event_btnAddNewStudentKeyReleased

    private void btnSearchExistingStudentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSearchExistingStudentKeyReleased
//        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
//            btnViewAllStudents.requestFocusInWindow();
//        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
//            btnAddNewStudent.requestFocusInWindow();
//        }
    }//GEN-LAST:event_btnSearchExistingStudentKeyReleased

    private void btnAddNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewStudentActionPerformed
        new StudentRegistrationForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddNewStudentActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        KeyboardFocusManager focusManager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        focusManager.addKeyEventPostProcessor(new KeyEventPostProcessor() {
            @Override
            public boolean postProcessKeyEvent(java.awt.event.KeyEvent e) {
                if (e.getID() == java.awt.event.KeyEvent.KEY_RELEASED) {
                    if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                        Window windowForComponent = SwingUtilities.windowForComponent((Component) e.getSource());
                        if (windowForComponent == null) return false;
                        windowForComponent.dispose();
                    }
                }
                return false;
            }
        });
    }//GEN-LAST:event_formWindowOpened

    private void btnSearchExistingStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchExistingStudentActionPerformed
       this.dispose();
        new SearchStudent(null, true).setVisible(true);
        
    }//GEN-LAST:event_btnSearchExistingStudentActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewStudent;
    private javax.swing.JButton btnSearchExistingStudent;
    // End of variables declaration//GEN-END:variables
}
