/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.paymentsystem.view;

import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import lk.ijse.paymentsystem.controller.ControllerFactory;
import lk.ijse.paymentsystem.controller.custom.StudentController;
import lk.ijse.paymentsystem.dto.StudentDTO;
import lk.ijse.paymentsystem.view.panels.AllStudents;
import lk.ijse.paymentsystem.view.panels.StudentDetails;
import lk.ijse.paymentsystem.view.panels.StudentDetailsSearch;
import lk.ijse.paymentsystem.view.utils.DSTextComponents;

/**
 *
 * @author Ranjith Suranga
 */
public class SearchStudent extends javax.swing.JDialog {

    private DSTextComponents textComponents;
    private AllStudents allStudent = null;
    private StudentDetails studentDetails = null;
    private StudentDetailsSearch studentDetailsSearch = null;
    /**
     * Creates new form SearchStudent
     */
    public SearchStudent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(0xFFFFFF));

//        ImageIcon frameIcon = new ImageIcon(this.getClass().getResource("/lk/ijse/academic_results_system_admin/icons/search_existing_student.png"));
//        setIconImage(frameIcon.getImage());

        cmbBoxBatch.setVisible(false);
        textComponents = new DSTextComponents(this.getContentPane());  
        rdiBtnNicItemStateChanged(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpSearch = new javax.swing.ButtonGroup();
        rdiBtnNic = new javax.swing.JRadioButton();
        rdiBtnName = new javax.swing.JRadioButton();
        lblSearchTitle = new javax.swing.JLabel();
        pnlParentContainer = new javax.swing.JPanel();
        pnlContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        rdiBtnStudentId = new javax.swing.JRadioButton();
        cmbBoxBatch = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search an Existing Student - Manage Students | IJSE - Academic Results System");
        setResizable(false);

        btnGrpSearch.add(rdiBtnNic);
        rdiBtnNic.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rdiBtnNic.setMnemonic('N');
        rdiBtnNic.setSelected(true);
        rdiBtnNic.setText("via NIC");
        rdiBtnNic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdiBtnNic.setFocusPainted(false);
        rdiBtnNic.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdiBtnNicItemStateChanged(evt);
            }
        });

        btnGrpSearch.add(rdiBtnName);
        rdiBtnName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rdiBtnName.setMnemonic('a');
        rdiBtnName.setText("via Name");
        rdiBtnName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdiBtnName.setFocusPainted(false);
        rdiBtnName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdiBtnNameItemStateChanged(evt);
            }
        });

        lblSearchTitle.setDisplayedMnemonic('t');
        lblSearchTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSearchTitle.setLabelFor(txtSearch);
        lblSearchTitle.setText("Enter the student's NIC to search");

        pnlContainer.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnlParentContainerLayout = new javax.swing.GroupLayout(pnlParentContainer);
        pnlParentContainer.setLayout(pnlParentContainerLayout);
        pnlParentContainerLayout.setHorizontalGroup(
            pnlParentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParentContainerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnlParentContainerLayout.setVerticalGroup(
            pnlParentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParentContainerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setFocusPainted(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(0, 0, 0))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSearch, txtSearch});

        btnGrpSearch.add(rdiBtnStudentId);
        rdiBtnStudentId.setText("via Student ID");
        rdiBtnStudentId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdiBtnStudentIdItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlParentContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdiBtnNic)
                        .addGap(18, 18, 18)
                        .addComponent(rdiBtnName)
                        .addGap(18, 18, 18)
                        .addComponent(rdiBtnStudentId)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cmbBoxBatch, 0, 285, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdiBtnNic)
                    .addComponent(rdiBtnName)
                    .addComponent(rdiBtnStudentId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSearchTitle)
                    .addComponent(cmbBoxBatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(pnlParentContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdiBtnNicItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdiBtnNicItemStateChanged
        rdiBtnNic.setFont(rdiBtnNic.getFont().deriveFont(Font.BOLD));
        rdiBtnName.setFont(rdiBtnName.getFont().deriveFont(Font.PLAIN));
        rdiBtnStudentId.setFont(rdiBtnStudentId.getFont().deriveFont(Font.PLAIN));
        
        rdiBtnNic.setForeground(Color.BLUE);
        rdiBtnName.setForeground(Color.BLACK);
        rdiBtnStudentId.setForeground(Color.BLACK);
        btnSearch.setVisible(true);
        
        studentDetails = new StudentDetails();
        pnlContainer.removeAll();
        pnlContainer.add(studentDetails);
        pnlContainer.setSize(studentDetails.getSize());
        pnlContainer.updateUI();
        pack();
        setLocationRelativeTo(null);   
        
        lblSearchTitle.setText("Enter the student's NIC to search");
        cmbBoxBatch.setVisible(false);
    }//GEN-LAST:event_rdiBtnNicItemStateChanged

    private void rdiBtnNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdiBtnNameItemStateChanged
        rdiBtnNic.setFont(rdiBtnNic.getFont().deriveFont(Font.PLAIN));
        rdiBtnName.setFont(rdiBtnName.getFont().deriveFont(Font.BOLD));
        rdiBtnStudentId.setFont(rdiBtnStudentId.getFont().deriveFont(Font.PLAIN));
        
        rdiBtnNic.setForeground(Color.BLACK);
        rdiBtnName.setForeground(Color.BLUE); 
        rdiBtnStudentId.setForeground(Color.BLACK);
        btnSearch.setVisible(false);
        cmbBoxBatch.setVisible(false);
        
        allStudent = new AllStudents();
        pnlContainer.removeAll();
        pnlContainer.add(allStudent);
        pnlContainer.setSize(allStudent.getSize());
        pnlContainer.updateUI();
        pack();
        setLocationRelativeTo(null);               
        
        lblSearchTitle.setText("Enter the student's Name to search");
        
    }//GEN-LAST:event_rdiBtnNameItemStateChanged

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        StudentController student = (StudentController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.STUDENT);
        
        if (rdiBtnNic.isSelected()) {
            try {
                StudentDTO studentDTO = student.search(txtSearch.getText());
                if (studentDTO != null) {
                    studentDetails.showDetails(studentDTO);
                }
            } catch (Exception ex) {
                Logger.getLogger(SearchStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if (rdiBtnName.isSelected()) {
            
        }else{
            
        }
    }//GEN-LAST:event_btnSearchActionPerformed
        
    private void rdiBtnStudentIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdiBtnStudentIdItemStateChanged
        rdiBtnNic.setFont(rdiBtnNic.getFont().deriveFont(Font.PLAIN));
        rdiBtnName.setFont(rdiBtnName.getFont().deriveFont(Font.PLAIN));
        rdiBtnStudentId.setFont(rdiBtnStudentId.getFont().deriveFont(Font.BOLD));
        
        rdiBtnNic.setForeground(Color.BLACK);
        rdiBtnName.setForeground(Color.BLACK);
        rdiBtnStudentId.setForeground(Color.BLUE);
        btnSearch.setVisible(true);
        
        studentDetailsSearch = new StudentDetailsSearch();
       
        pnlContainer.removeAll();
        pnlContainer.add(studentDetailsSearch);
        pnlContainer.setSize(studentDetailsSearch.getSize());
        pnlContainer.updateUI();
        pack();
        setLocationRelativeTo(null);               
        
        lblSearchTitle.setText("Enter the student's ID and Select Batch to search");
        cmbBoxBatch.setVisible(true);
    }//GEN-LAST:event_rdiBtnStudentIdItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpSearch;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbBoxBatch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSearchTitle;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlParentContainer;
    private javax.swing.JRadioButton rdiBtnName;
    private javax.swing.JRadioButton rdiBtnNic;
    private javax.swing.JRadioButton rdiBtnStudentId;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
