/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.paymentsystem.view;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import lk.ijse.paymentsystem.view.panels.AllStudents;
import lk.ijse.paymentsystem.view.panels.StudentDetails;
import lk.ijse.paymentsystem.view.panels.StudentDetailsSearch;
import lk.ijse.paymentsystem.view.utils.DSTextComponents;

/**
 *
 * @author Ranjith Suranga
 */
public class SearchStudent extends javax.swing.JDialog {

    private DSTextComponents textComponents;
    /**
     * Creates new form SearchStudent
     */
    public SearchStudent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(0xFFFFFF));

//        ImageIcon frameIcon = new ImageIcon(this.getClass().getResource("/lk/ijse/academic_results_system_admin/icons/search_existing_student.png"));
//        setIconImage(frameIcon.getImage());

        cmbBoxBatch.setVisible(false);
        textComponents = new DSTextComponents(this.getContentPane());  
        rdoNICItemStateChanged(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpSearch = new javax.swing.ButtonGroup();
        rdoNIC = new javax.swing.JRadioButton();
        rdoName = new javax.swing.JRadioButton();
        lblSearchTitle = new javax.swing.JLabel();
        pnlParentContainer = new javax.swing.JPanel();
        pnlContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        rdoStudentId = new javax.swing.JRadioButton();
        cmbBoxBatch = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search an Existing Student - Manage Students | IJSE - Academic Results System");
        setResizable(false);

        btnGrpSearch.add(rdoNIC);
        rdoNIC.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rdoNIC.setMnemonic('N');
        rdoNIC.setSelected(true);
        rdoNIC.setText("via NIC");
        rdoNIC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoNIC.setFocusPainted(false);
        rdoNIC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdoNICItemStateChanged(evt);
            }
        });

        btnGrpSearch.add(rdoName);
        rdoName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rdoName.setMnemonic('a');
        rdoName.setText("via Name");
        rdoName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoName.setFocusPainted(false);
        rdoName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdoNameItemStateChanged(evt);
            }
        });

        lblSearchTitle.setDisplayedMnemonic('t');
        lblSearchTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSearchTitle.setLabelFor(txtSearch);
        lblSearchTitle.setText("Enter the student's NIC to search");

        pnlContainer.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnlParentContainerLayout = new javax.swing.GroupLayout(pnlParentContainer);
        pnlParentContainer.setLayout(pnlParentContainerLayout);
        pnlParentContainerLayout.setHorizontalGroup(
            pnlParentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParentContainerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnlParentContainerLayout.setVerticalGroup(
            pnlParentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParentContainerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setFocusPainted(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(0, 0, 0))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSearch, txtSearch});

        btnGrpSearch.add(rdoStudentId);
        rdoStudentId.setText("via Student ID");
        rdoStudentId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdoStudentIdItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlParentContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoNIC)
                        .addGap(18, 18, 18)
                        .addComponent(rdoName)
                        .addGap(18, 18, 18)
                        .addComponent(rdoStudentId)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cmbBoxBatch, 0, 285, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNIC)
                    .addComponent(rdoName)
                    .addComponent(rdoStudentId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSearchTitle)
                    .addComponent(cmbBoxBatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(pnlParentContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoNICItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdoNICItemStateChanged
        rdoNIC.setFont(rdoNIC.getFont().deriveFont(Font.BOLD));
        rdoName.setFont(rdoName.getFont().deriveFont(Font.PLAIN));
        rdoStudentId.setFont(rdoStudentId.getFont().deriveFont(Font.PLAIN));
        
        rdoNIC.setForeground(Color.BLUE);
        rdoName.setForeground(Color.BLACK);
        rdoStudentId.setForeground(Color.BLACK);
        btnSearch.setVisible(true);
        
        StudentDetails pnlStudentDetails = new StudentDetails();
        pnlContainer.removeAll();
        pnlContainer.add(pnlStudentDetails);
        pnlContainer.setSize(pnlStudentDetails.getSize());
        pnlContainer.updateUI();
        pack();
        setLocationRelativeTo(null);   
        
        lblSearchTitle.setText("Enter the student's NIC to search");
        cmbBoxBatch.setVisible(false);
    }//GEN-LAST:event_rdoNICItemStateChanged

    private void rdoNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdoNameItemStateChanged
        rdoNIC.setFont(rdoNIC.getFont().deriveFont(Font.PLAIN));
        rdoName.setFont(rdoName.getFont().deriveFont(Font.BOLD));
        rdoStudentId.setFont(rdoStudentId.getFont().deriveFont(Font.PLAIN));
        
        rdoNIC.setForeground(Color.BLACK);
        rdoName.setForeground(Color.BLUE); 
        rdoStudentId.setForeground(Color.BLACK);
        btnSearch.setVisible(false);
        cmbBoxBatch.setVisible(false);
        AllStudents pnlAllStudents = new AllStudents();
        pnlContainer.removeAll();
        pnlContainer.add(pnlAllStudents);
        pnlContainer.setSize(pnlAllStudents.getSize());
        pnlContainer.updateUI();
        pack();
        setLocationRelativeTo(null);               
        
        lblSearchTitle.setText("Enter the student's Name to search");
        
    }//GEN-LAST:event_rdoNameItemStateChanged

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    }//GEN-LAST:event_btnSearchActionPerformed
        
    private void rdoStudentIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdoStudentIdItemStateChanged
        rdoNIC.setFont(rdoNIC.getFont().deriveFont(Font.PLAIN));
        rdoName.setFont(rdoName.getFont().deriveFont(Font.PLAIN));
        rdoStudentId.setFont(rdoStudentId.getFont().deriveFont(Font.BOLD));
        
        rdoNIC.setForeground(Color.BLACK);
        rdoName.setForeground(Color.BLACK);
        rdoStudentId.setForeground(Color.BLUE);
        btnSearch.setVisible(true);
        
        StudentDetailsSearch pnlStudentDetailsSearch = new StudentDetailsSearch();
       
        pnlContainer.removeAll();
        pnlContainer.add(pnlStudentDetailsSearch);
        pnlContainer.setSize(pnlStudentDetailsSearch.getSize());
        pnlContainer.updateUI();
        pack();
        setLocationRelativeTo(null);               
        
        lblSearchTitle.setText("Enter the student's ID and Select Batch to search");
        cmbBoxBatch.setVisible(true);
    }//GEN-LAST:event_rdoStudentIdItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpSearch;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbBoxBatch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSearchTitle;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlParentContainer;
    private javax.swing.JRadioButton rdoNIC;
    private javax.swing.JRadioButton rdoName;
    private javax.swing.JRadioButton rdoStudentId;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
