/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.paymentsystem.view;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.paymentsystem.controller.ControllerFactory;
import lk.ijse.paymentsystem.controller.custom.StudentController;
import lk.ijse.paymentsystem.dto.RegistrationDTO;
import lk.ijse.paymentsystem.dto.StudentDTO;

/**
 *
 * @author simo-ds
 */
public class StudentDetails extends javax.swing.JFrame {

    private StudentController studentController;
    private String sid;
//    private StudentDTO student1 = null;

    /**
     * Creates new form StudentDetails
     */
    public StudentDetails() {
        initComponents();
        setLocationRelativeTo(null);
        rdiBtnMale.setEnabled(false);
        rdiBtnFemale.setEnabled(false);
        this.getContentPane().setBackground(Color.WHITE);
        setDefaultCloseOperation(2);
    }

    public StudentDetails(String sid,StudentDTO student1) {
//        super(title);
        this();
//        this.student1 = student1;
        this.sid = sid;
        setValues(student1);

    }

    public void setValues(StudentDTO student1) {
        if (student1 != null) {
            lblNameWithInitials.setText(student1.getInitialStudentName());
            lblName.setText(student1.getStudentName());
            lblPersonalAddress1.setText(student1.getAddressLine1());
            lblPersonalAddress2.setText(student1.getAddressLine2());
            lblPersonalAddress3.setText(student1.getAddressLine3());
            lblHomeTel.setText(student1.getTelHome());
            lblMobileTel.setText(student1.getMobile());
            lblMail.setText(student1.getEmail());
            lblId.setText(student1.getNic());
            String[] dob = student1.getDob().split("-");
            lblBirthYear.setText(dob[0]);
            lblBirthMonth.setText(dob[1]);
            lblBirthDay.setText(dob[2]);
            if (student1.getGender()) {
                rdiBtnMale.setSelected(true);
            } else {
                rdiBtnFemale.setSelected(true);
            }

            lblSchoolStu.setText(student1.getSchool());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblSubTitle = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblTelephone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNic = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblSchool = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblMobile = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblMonth = new javax.swing.JLabel();
        lblDay = new javax.swing.JLabel();
        rdiBtnMale = new javax.swing.JRadioButton();
        rdiBtnFemale = new javax.swing.JRadioButton();
        lblSchoolStu = new javax.swing.JLabel();
        lblNameWithInitials2 = new javax.swing.JLabel();
        lblNameWithInitials = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPersonalAddress1 = new javax.swing.JLabel();
        lblPersonalAddress2 = new javax.swing.JLabel();
        lblPersonalAddress3 = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblHomeTel = new javax.swing.JLabel();
        lblMobileTel = new javax.swing.JLabel();
        lblBirthYear = new javax.swing.JLabel();
        lblBirthMonth = new javax.swing.JLabel();
        lblBirthDay = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/paymentsystem/images/ijse-logo.gif"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSubTitle.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblSubTitle.setText("PERSONAL DETAILS");
        jPanel1.add(lblSubTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblFullName.setDisplayedMnemonic('N');
        lblFullName.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblFullName.setText("Full Name:");
        jPanel1.add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        lblAddress.setDisplayedMnemonic('o');
        lblAddress.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblAddress.setText("Personal Address:");
        jPanel1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        lblTelephone.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblTelephone.setText("Telephone:");
        jPanel1.add(lblTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        lblEmail.setDisplayedMnemonic('E');
        lblEmail.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblEmail.setText("E-mail:");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        lblNic.setDisplayedMnemonic('c');
        lblNic.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblNic.setText("NIC:");
        jPanel1.add(lblNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        lblDateOfBirth.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblDateOfBirth.setText("Date of Birth:");
        jPanel1.add(lblDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        lblGender.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblGender.setText("Gender:");
        jPanel1.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        lblSchool.setDisplayedMnemonic('S');
        lblSchool.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblSchool.setText("School:");
        jPanel1.add(lblSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        lblHome.setDisplayedMnemonic('H');
        lblHome.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblHome.setText("Home:");
        jPanel1.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        lblMobile.setDisplayedMnemonic('b');
        lblMobile.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblMobile.setText("Mobile:");
        jPanel1.add(lblMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        lblYear.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblYear.setText("Year:");
        jPanel1.add(lblYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        lblMonth.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblMonth.setText("Month:");
        jPanel1.add(lblMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        lblDay.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblDay.setText("Day:");
        jPanel1.add(lblDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        buttonGroup1.add(rdiBtnMale);
        rdiBtnMale.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        rdiBtnMale.setText("Male");
        rdiBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdiBtnMaleActionPerformed(evt);
            }
        });
        jPanel1.add(rdiBtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        buttonGroup1.add(rdiBtnFemale);
        rdiBtnFemale.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        rdiBtnFemale.setText("Female");
        jPanel1.add(rdiBtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        lblSchoolStu.setDisplayedMnemonic('t');
        lblSchoolStu.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblSchoolStu.setText("xxxx");
        lblSchoolStu.setToolTipText("");
        jPanel1.add(lblSchoolStu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 430, 20));

        lblNameWithInitials2.setDisplayedMnemonic('t');
        lblNameWithInitials2.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblNameWithInitials2.setText("Name with Initials:");
        lblNameWithInitials2.setToolTipText("");
        jPanel1.add(lblNameWithInitials2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        lblNameWithInitials.setDisplayedMnemonic('t');
        lblNameWithInitials.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblNameWithInitials.setText("xxxx");
        lblNameWithInitials.setToolTipText("");
        jPanel1.add(lblNameWithInitials, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 430, 20));

        lblName.setDisplayedMnemonic('t');
        lblName.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblName.setText("xxxx");
        lblName.setToolTipText("");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 430, 20));

        lblPersonalAddress1.setDisplayedMnemonic('t');
        lblPersonalAddress1.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblPersonalAddress1.setText("xxxx");
        lblPersonalAddress1.setToolTipText("");
        jPanel1.add(lblPersonalAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 430, 20));

        lblPersonalAddress2.setDisplayedMnemonic('t');
        lblPersonalAddress2.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblPersonalAddress2.setText("xxxx");
        lblPersonalAddress2.setToolTipText("");
        jPanel1.add(lblPersonalAddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 430, 20));

        lblPersonalAddress3.setDisplayedMnemonic('t');
        lblPersonalAddress3.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblPersonalAddress3.setText("xxxx");
        lblPersonalAddress3.setToolTipText("");
        jPanel1.add(lblPersonalAddress3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 430, 20));

        lblMail.setDisplayedMnemonic('t');
        lblMail.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblMail.setText("xxxx");
        lblMail.setToolTipText("");
        jPanel1.add(lblMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 430, 20));

        lblId.setDisplayedMnemonic('t');
        lblId.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblId.setText("xxxx");
        lblId.setToolTipText("");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 430, 20));

        lblHomeTel.setDisplayedMnemonic('t');
        lblHomeTel.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblHomeTel.setText("xxxx");
        lblHomeTel.setToolTipText("");
        jPanel1.add(lblHomeTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 150, 20));

        lblMobileTel.setDisplayedMnemonic('t');
        lblMobileTel.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblMobileTel.setText("xxxx");
        lblMobileTel.setToolTipText("");
        jPanel1.add(lblMobileTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 150, 20));

        lblBirthYear.setDisplayedMnemonic('t');
        lblBirthYear.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblBirthYear.setText("xxxx");
        lblBirthYear.setToolTipText("");
        jPanel1.add(lblBirthYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 80, 20));

        lblBirthMonth.setDisplayedMnemonic('t');
        lblBirthMonth.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblBirthMonth.setText("xxxx");
        lblBirthMonth.setToolTipText("");
        jPanel1.add(lblBirthMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 80, 20));

        lblBirthDay.setDisplayedMnemonic('t');
        lblBirthDay.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lblBirthDay.setText("xxxx");
        lblBirthDay.setToolTipText("");
        jPanel1.add(lblBirthDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 80, 20));

        btnConfirm.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/paymentsystem/icons/add.png"))); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.setToolTipText("Click to add a new student");
        btnConfirm.setPreferredSize(new java.awt.Dimension(127, 39));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnGoBack.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/paymentsystem/icons/back1600 edit.png"))); // NOI18N
        btnGoBack.setMnemonic('G');
        btnGoBack.setText("Go Back");
        btnGoBack.setToolTipText("Click to add a new student");
        btnGoBack.setPreferredSize(new java.awt.Dimension(127, 39));
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        btnGoBack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnGoBackKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdiBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdiBtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdiBtnMaleActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        RegistrationDTO registrationDTO = new RegistrationDTO();
        registrationDTO.setSID(sid);
        RegistrationDTO registration = null;
        try {
            registration = (RegistrationDTO) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.REGISTRATION).search(registrationDTO);
        } catch (Exception ex) {
            Logger.getLogger(StudentDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (registration != null) {
//            PaymentForRegistrationCourse paymentForm = new PaymentForRegistrationCourse(sid);
//            paymentForm.setVisible(true);
//            CourseDetails courseDetails = new CourseDetails(sid);
//            courseDetails.setVisible(true);
               JOptionPane.showMessageDialog(null, "Student has already registered for a course.");
               
        } else {
            CourseDetails courseDetails = new CourseDetails(sid);
            courseDetails.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnGoBackKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGoBackKeyReleased

    }//GEN-LAST:event_btnGoBackKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnGoBack;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBirthDay;
    private javax.swing.JLabel lblBirthMonth;
    private javax.swing.JLabel lblBirthYear;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblHomeTel;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblMobileTel;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameWithInitials;
    private javax.swing.JLabel lblNameWithInitials2;
    private javax.swing.JLabel lblNic;
    private javax.swing.JLabel lblPersonalAddress1;
    private javax.swing.JLabel lblPersonalAddress2;
    private javax.swing.JLabel lblPersonalAddress3;
    private javax.swing.JLabel lblSchool;
    private javax.swing.JLabel lblSchoolStu;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblYear;
    private javax.swing.JRadioButton rdiBtnFemale;
    private javax.swing.JRadioButton rdiBtnMale;
    // End of variables declaration//GEN-END:variables
}
